Improved: Upgrade to gradle 7.3 to support jdk 17 (OFBIZ-12400)
apache/ofbiz-framework pull request #354
Opened 2021-11-24 10:52 UTC by ieugen

Improved: Upgrade to gradle 7.3 to support jdk 17 (OFBIZ-12400)

2021-12-12 09:30 UTC, JacquesLeRoux requested changes
Hi Eugen,

I tried on Win7 (I guess it's unrelated to the issue) with openjdk version "1.8.0_202" and got:

```
C:\projectsASF\Git\ofbiz-framework>gradlew --no-daemon --stacktrace
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.3/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build

> Configure project :
You are using one or more deprecated Asciidoctor Gradle plugin features. To help with migration run with --warning-mode=all.

> Task :compileJava FAILED
> Task :nodeSetup UP-TO-DATE
> Task :npmSetup SKIPPED
> Task :npmInstall UP-TO-DATE

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Error while evaluating property 'javaVersion' of task ':compileJava'
   > java.lang.NullPointerException (no error message)

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileJava'.
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:402)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:389)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:382)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:368)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
Caused by: org.gradle.api.internal.tasks.properties.PropertyEvaluationException: Error while evaluating property 'javaVersion' of task ':compileJava'
        at org.gradle.api.internal.tasks.properties.InputParameterUtils.prepareInputParameterValue(InputParameterUtils.java:33)
        at org.gradle.api.internal.tasks.execution.TaskExecution.lambda$visitRegularInputs$1(TaskExecution.java:312)
        at org.gradle.internal.execution.fingerprint.impl.DefaultInputFingerprinter$InputCollectingVisitor.visitInputProperty(DefaultInputFingerprinter.java:95)
        at org.gradle.api.internal.tasks.execution.TaskExecution.visitRegularInputs(TaskExecution.java:312)
        at org.gradle.internal.execution.fingerprint.impl.DefaultInputFingerprinter.fingerprintInputProperties(DefaultInputFingerprinter.java:54)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.captureExecutionStateWithOutputs(CaptureStateBeforeExecutionStep.java:193)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.lambda$captureExecutionState$1(CaptureStateBeforeExecutionStep.java:141)
        at org.gradle.internal.execution.steps.BuildOperationStep$1.call(BuildOperationStep.java:37)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.internal.execution.steps.BuildOperationStep.operation(BuildOperationStep.java:34)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.captureExecutionState(CaptureStateBeforeExecutionStep.java:130)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.lambda$execute$0(CaptureStateBeforeExecutionStep.java:75)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:75)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:50)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:93)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:93)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
        at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:43)
        at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:31)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:40)
        at org.gradle.api.internal.tasks.execution.TaskExecution$3.withWorkspace(TaskExecution.java:284)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:40)
        at org.gradle. [...]

2021-12-12 09:37 UTC, JacquesLeRoux commented
I was also interested because I wanted to test the SpotBugs Gradle plugin that can't run with current Gradle version (6.5).

I noticed this that seems a too early typo from Gradle team:

> Deprecated Gradle features were used in this build, making it incompatible with **_Gradle 8.0._**

2021-12-13 07:32 UTC, ieugen commented
Hi @JacquesLeRoux  If I had access to a windows I believe I can fix this.
I think it should be a gradle config change only.

Can we do automated builds on windows as well?

2021-12-13 08:04 UTC, ieugen commented
@JacquesLeRoux : I forced pushed some changes that might fix this.

```
sourceCompatibility = '1.8'
targetCompatibility = '1.8'
```
was updated to
 
```
java {
    sourceCompatibility(JavaVersion.VERSION_1_8)
    targetCompatibility(JavaVersion.VERSION_1_8)
}
```

https://docs.gradle.org/current/userguide/java_plugin.html#sec:java-extension

See deprecated options: https://docs.gradle.org/current/dsl/org.gradle.api.plugins.JavaPluginConvention.html

2021-12-13 09:21 UTC, JacquesLeRoux commented
Hi Eugen,

No we don't do automated builds on Windows. And at the moment we don't even have BuildBot running (for 2 months).

On Windows I have tried with <<openjdk version "11.0.2" 2019-01-15>> same issue.

I then tried on Ubuntu 13.10 and got another issue related to Groovy:

```
jacques@jacques-VirtualBox:~/asfprojects/ofbiz-framework$ ./gradlew --stacktrace 

> Configure project :
You are using one or more deprecated Asciidoctor Gradle plugin features. To help with migration run with --warning-mode=all.

> Task :compileJava UP-TO-DATE
> Task :compileGroovy FAILED
> Task :nodeSetup UP-TO-DATE
> Task :npmSetup SKIPPED
> Task :npmInstall UP-TO-DATE

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovy'.
> Failed to run Gradle Worker Daemon
   > Process 'Gradle Worker Daemon 4' finished with non-zero exit value 137

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileGroovy'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:145)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:143)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:402)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:389)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:382)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:368)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
Caused by: org.gradle.process.internal.worker.WorkerProcessException: Failed to run Gradle Worker Daemon
	at org.gradle.process.internal.worker.WorkerProcessException.runFailed(WorkerProcessException.java:29)
	at org.gradle.process.internal.worker.DefaultMultiRequestWorkerProcessBuilder$1.run(DefaultMultiRequestWorkerProcessBuilder.java:192)
	at org.gradle.workers.internal.WorkerDaemonClient.execute(WorkerDaemonClient.java:46)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.WorkerDaemonFactory$1.execute(WorkerDaemonFactory.java:44)
	at org.gradle.workers.internal.AbstractWorker.execute(AbstractWorker.java:37)
	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler.execute(AbstractDaemonCompiler.java:61)
	at org.gradle.api.internal.tasks.compile.NormalizingGroovyCompiler.delegateAndHandleErrors(NormalizingGroovyCompiler.java:137)
	at org.gradle.api.internal.tasks.compile.NormalizingGroovyCompiler.lambda$execute$0(NormalizingGroovyCompiler.java:55)
	at org.gradle.api.internal.tasks.compile.NormalizingGroovyCompiler.withResolvedClasspath(NormalizingGroovyCompiler.java:62)
	at org.gradle.api.internal.tasks.compile.NormalizingGroovyCompiler.execute(NormalizingGroovyCompiler.java:50)
	at org.gradle.api.internal.tasks.compile.NormalizingGroovyCompiler.execute(NormalizingGroovyCompiler.java:40)
	at org.gradle.api.internal.tasks.compile.AnnotationProcessorDiscoveringCompiler.execute(AnnotationProcessorDiscoveringCompiler.java:51)
	at org.gradle.api.internal.tasks.compile.AnnotationProcessorDiscoveringCompiler.execute(AnnotationProcessorDiscoveringCompiler.java:37)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompiler.execute(CleaningJavaCompiler.java:53)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompiler.execute(CleaningJavaCompiler.java:32)
	at org.gradle.api.tasks.compile.GroovyCompile.compile(GroovyCompi [...]

2021-12-14 08:44 UTC, JacquesLeRoux commented
Hi @ieugen ,

I confirm it works for the trunk with Gradle 7.1.1 as can be seen here: https://ci2.apache.org/#/builders/46/builds/14 (gradle wrapper step)

2021-12-14 15:22 UTC, ieugen commented
@JacquesLeRoux : I just bought a Windows 10 license and I will try to build it there once I set it up.

2021-12-16 15:07 UTC, JacquesLeRoux commented
Hi @ieugen ,

I wrote above that 
> it works on latest Ubuntu for the trunk with Gradle 7.1.1 

That's true for the framework only build. But for the framework+plugins build (where w/ AsciiDoctor we create all the documentation for both framework and plugins) it fails, see: https://ci2.apache.org/#/builders/46/builds/17 ( generateReadmeFiles step)

2021-12-16 15:19 UTC, PierreSmits commented
Hi Jacques,
It seems to me that this has more to do with the asciidoctor stuff, than gradle itself. Won't you agree? And then more particular with the aspect that it is implemented differently in ofbiz-plugins compared to ofbiz-framework. Correct?

if it works for framework builds, then it should also work for ofbiz-framework+ofbiz-plugin builds.

2021-12-16 15:48 UTC, JacquesLeRoux commented
Hi Pierre,

There is no use of any Asciidoc task in framework only build.

2021-12-16 23:55 UTC, ieugen commented
The build work on my machine:
```
------------------------------------------------------------

Build time:   2021-12-01 15:42:20 UTC
Revision:     2c62cec93e0b15a7d2cd68746f3348796d6d42bd

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.13 (Eclipse Adoptium 11.0.13+8)
OS:           Windows 10 10.0 amd64

PS C:\Users\ieugen\IdeaProjects\ofbiz-framework> .\gradlew.bat build       

> Configure project :
You are using one or more deprecated Asciidoctor Gradle plugin features. To help with migration run with --w
arning-mode=all.

> Task :compileJava UP-TO-DATE
> Task :compileGroovy UP-TO-DATE
> Task :nodeSetup UP-TO-DATE
> Task :npmSetup SKIPPED    
> Task :processResources UP-TO-DATE       
> Task :classes UP-TO-DATE                
> Task :compileGroovyScriptsJava NO-SOURCE
> Task :compileTestJava UP-TO-DATE
> Task :npmInstall UP-TO-DATE     
> Task :jar UP-TO-DATE            
> Task :startScripts UP-TO-DATE   

> Task :distTar
Execution optimizations have been disabled for task ':distTar' to ensure correctness due to the following re
asons:
  - Gradle detected a problem with the following location: 'C:\Users\ieugen\IdeaProjects\ofbiz-framework'. R
eason: Task ':distTar' uses this output of task ':npmInstall' without declaring an explicit or implicit depe
ndency. This can lead to incorrect results being produced, depending on what order the tasks are executed. P
lease refer to https://docs.gradle.org/7.3.1/userguide/validation_problems.html#implicit_dependency for more
 details about this problem.

> Task :distZip
Execution optimizations have been disabled for task ':distZip' to ensure correctness due to the following re
asons:
  - Gradle detected a problem with the following location: 'C:\Users\ieugen\IdeaProjects\ofbiz-framework'. R
eason: Task ':distZip' uses this output of task ':npmInstall' without declaring an explicit or implicit depe
ndency. This can lead to incorrect results being produced, depending on what order the tasks are executed. P
lease refer to https://docs.gradle.org/7.3.1/userguide/validation_problems.html#implicit_dependency for more
 details about this problem.

> Task :assemble
> Task :compileGroovyScriptsGroovy SKIPPED
> Task :processGroovyScriptsResources NO-SOURCE
> Task :groovyScriptsClasses UP-TO-DATE
> Task :checkstyleGroovyScripts NO-SOURCE
> Task :checkstyleMain UP-TO-DATE
> Task :compileTestGroovy UP-TO-DATE
> Task :processTestResources UP-TO-DATE
> Task :testClasses UP-TO-DATE
> Task :checkstyleTest UP-TO-DATE
> Task :test UP-TO-DATE
> Task :check UP-TO-DATE
> Task :build

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from
 your own scripts or plugins.

See https://docs.gradle.org/7.3.1/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 2 invalid unit(s) of work during this build to ensure correct
ness.
Please consult deprecation warnings for more details.

BUILD SUCCESSFUL in 43s
15 actionable tasks: 2 executed, 13 up-to-date

```

```
java -version
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)
```

2021-12-17 04:23 UTC, JacquesLeRoux commented
Hi @ieugen,

Could you please try one of the AsciiDoc tasks, like generateReadmeFiles

2021-12-17 07:46 UTC, ieugen commented
I had to upgrade asciidoctorj to 3.x branch and disabled pdf generation on Windows.
I think we can live with that for a time being. 
AsciidoctorJ with pdf / Jruby has issues on Windows - no reason to suffer. 

From what I know, most efforts in asciidoc are geared towards Antora .
It might alsobe easier to keep docs in a single place - mirror the directory structure maybe.

Build scan is here: https://scans.gradle.com/s/5pqew45l23cjy  (gradle ....  --scan )
The same build on linux: https://scans.gradle.com/s/vfjbw5ehcf5se

2021-12-17 07:47 UTC, ieugen commented
PDF's migh work if we install the proper dependencies perhaps.
I don't have time for that right now. 

```
dec. 17, 2021 9:44:08 A.M. uri:classloader:/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb convert_paragraph
WARNING: could not embed image: /tmp/image-20211217-362553-10q2vwo.svg?branch=trunk; image file is an unrecognised format; install prawn-gmagick gem to add support
dec. 17, 2021 9:44:08 A.M. uri:classloader:/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb convert_paragraph
WARNING: could not embed image: /tmp/image-20211217-362553-g4vld1; image file is an unrecognised format; install prawn-gmagick gem to add support
```

2021-12-17 07:55 UTC, ieugen commented
@JacquesLeRoux :  Ubuntu 13.10  is ancient and also not supported. 
If you like to use Linux and Ubuntu please use a LTS version - See https://wiki.ubuntu.com/Releases . 
They are always xx.04 veresioned and latest is 20.04, before that 18.04 and 16.04 .

2021-12-17 08:26 UTC, mbrohl commented
> I had to upgrade asciidoctorj to 3.x branch and disabled pdf generation on Windows. I think we can live with that for a time being. AsciidoctorJ with pdf / Jruby has issues on Windows - no reason to suffer.

I think we should not introduce regressions or cut features during the upgrade, at least not without proper discussion. Please have in mind that users might rely on those features.

We are not on Windows, so cannot help there.

2021-12-17 08:38 UTC, ieugen commented
@mbrohl : Thanks for the reminder. 
I am well aware of that but sometimes it's un-avoidable.
The asciidoctor plugin 2.x was not working with gradle 7.x. 
There was a change in the gradle API. 

I am also not on Windows and it is a pain to use it, but I needed it for some work and decided to try and fix this.

2021-12-17 09:42 UTC, ieugen commented
@mbrohl : Enabling pdf output on windows craashes. 
The build scan for that is here https://scans.gradle.com/s/fejpzotdbk7ce  .

I also tried updating to 1.6.0 

```
asciidoctorj {
  modules {
    pdf {
      version '1.6.0'
    }
  }
}
```

2021-12-17 09:46 UTC, ieugen commented
I think this is related to our windows issues: https://github.com/asciidoctor/asciidoctor-pdf/issues/425

2021-12-17 10:02 UTC, JacquesLeRoux commented
Yes, that's it Eugen

2021-12-17 10:05 UTC, JacquesLeRoux commented
Hi guys,

When there are no clear conclusions, better discuss openly on dev ML, for the community to decide. This said, here is my opinion. 

I like your solution Eugen (I hate Ruby on Windows, never tried it on *nix). I generate AsciiDoc files on Windows only for test when necessary and that's very rare. I then don't care much about PDF, even if I have always tried to have it working on Win too, there are people out there who use Windows. I guess they don't use Win in production :smirk:. I believe people who generate their own documentation w/ AsciiDoc don't do it on Windows. So I think it's indeed OK, at least for the time being, seems we have a solution with https://github.com/asciidoctor/asciidoctor-pdf/issues/425

I rarely use Ubuntu (as a VM on Win), mostly to deal with the OFBiz site, installing PHP on Windows is not easy. Also I don't want to spend time on reinstalling Ubuntu on my VM almost only for that :smile:.

A bit related, for files like those under https://ci.apache.org/projects/ofbiz/site/ most of the time I rely on BuildBot which generates the files. But, as you certainly know, it's 2 months that BuildBot is not working (upgrading from 0.8 to 3.3.2). For few days I'm completing the work done by Gavin. Using AsciiDoc on 3.3.2 was part of it, hence the question I asked to you Eugen.

2021-12-17 10:12 UTC, ieugen commented
@JacquesLeRoux : you might want to try Windows subsystem for linux 2 if you don't want to use VM's. 
It might be good enough for your work. 

IMO not building pdf's on Windows because the tool we depend on has issues there is a small concession. 

I would argue that building A variant of the docs should not be a stopper for us - since asciidoc is still available and you don't need a reader for it - like you need for PDF. 

@mbrohl : are you ok with merging this?

2021-12-17 10:37 UTC, JacquesLeRoux commented
Eugen,

I don't want to upgrade upon Win7, at the max 8.1.

2021-12-17 11:37 UTC, PierreSmits commented
HI Ioan,

I like it too, and am not worried about the argument regarding 'introduce regressions or cut features during the upgrade' without proof being provided, or the argument regarding (unknown) users relying on this second class feature of OFBiz

However, may I suggest that you update the title, description and/or environment of the associated ticket? As you commented there about version 7.3 supporting also current JVM (8) and intermediate (11). The title of the ticket is what shows up in the release notes of a future release.

+1 for merging this.

2022-01-04 17:27 UTC, JacquesLeRoux commented
Hi All,

Actually issues also happen on last Ubuntu see https://issues.apache.org/jira/browse/OFBIZ-12476 ("README.PDF is not generated by BuildBot nor locally") for details

2022-11-29 10:37 UTC, ieugen commented
I've upgraded to gradle 7.6 and I can start ofbiz with jdk17 locally. 
I do see some errors but it runs.
Perhaps a few other libs will need to be upgraded.

![Screenshot from 20221129123549](https://user-images.githubusercontent.com/1050920/204507347-0e64da49-a99e-4e1f-841e-ad3c76f6b711.png)

2022-11-30 12:50 UTC, JacquesLeRoux commented
Hi Eugen,

I answered on dev ML so far and pushed 2 nonfunctional unrelated commits, WIP...

2022-11-30 12:50 UTC, JacquesLeRoux approved these changes

2023-01-28 11:17 UTC, JacquesLeRoux commented
This is now handled at https://issues.apache.org/jira/browse/OFBIZ-12400

2023-01-28 11:17 UTC, closed without merging